In [1]:
import numpy as np

Q1. 행렬 만들기

In [2]:
np.arange(10,90,10).reshape(2,4)

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [3]:
np.arange(1,9).reshape(2,4)*10

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [5]:
# 1
a = np.array([[10,20,30,40],[50,60,70,80]])
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

Q2. Indexing, Slicing

In [5]:
m = np.arange(15).reshape(3,5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [7]:
# 2-1, 2-2
m[1,2], m[-1,-1]

(7, 14)

In [8]:
# 2-3
m[1, 1:3]

array([6, 7])

In [9]:
# 2-4
m[1:,2]

array([ 7, 12])

In [10]:
m[1:,2:3]

array([[ 7],
       [12]])

In [11]:
# 2-5
m[:-1,3:]

array([[3, 4],
       [8, 9]])

In [12]:
# 2
m = np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9],[10, 11, 12, 13, 14]])
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [13]:
# 2-1)
m[1,2], m[-1,-1]

7

In [14]:
# 2-2)
m[2,4]

14

In [15]:
# 2-3)
m[1, 1:3]

array([6, 7])

In [16]:
# 2-4)
m[1:3,2]

array([ 7, 12])

In [17]:
# 2-5)
m[:2,3:]

array([[3, 4],
       [8, 9]])

In [ ]:
# Slicing 행과 열에 적용되는 결과

Q3. Boolean Indexing

In [13]:
# 3
f = m.flatten()
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
# 3-1
f[f % 3 == 0]

array([ 0,  3,  6,  9, 12])

In [15]:
# 3-2
f[f % 4 == 1]

array([ 1,  5,  9, 13])

In [16]:
f[np.logical_and(f%3==0, f%4==1)]

array([9])

In [36]:
# 3-3
a = np.logical_and(f % 3 == 0, f % 4 == 1)
f[a]

array([9])

Q4. 대각선 행렬

In [20]:
np.eye(5,5,-1,int)*3 + np.eye(5,5,0,int)*2 + np.eye(5,5,1,int)

array([[2, 1, 0, 0, 0],
       [3, 2, 1, 0, 0],
       [0, 3, 2, 1, 0],
       [0, 0, 3, 2, 1],
       [0, 0, 0, 3, 2]])

In [39]:
# 4
a = np.eye(N=5, M=5, dtype=np.int8)
b = np.eye(N=5, M=5, k=1, dtype=np.int8)
c = np.eye(N=5, M=5, k=-1, dtype=np.int8)
a*2 + b*1 +c*3


array([[2, 1, 0, 0, 0],
       [3, 2, 1, 0, 0],
       [0, 3, 2, 1, 0],
       [0, 0, 3, 2, 1],
       [0, 0, 0, 3, 2]], dtype=int8)

Q5. Matrix operation

In [21]:
np.random.seed(2021)
m = np.random.uniform(0,10,30).reshape(5, 6).round(4)
m

array([[6.0598, 7.3337, 1.3895, 3.1267, 9.9724, 1.2816],
       [1.7899, 7.5293, 6.6216, 7.8431, 0.9689, 0.5857],
       [9.624 , 6.1656, 0.8663, 5.6127, 6.1652, 9.6384],
       [5.743 , 3.7116, 4.5215, 2.0185, 5.6931, 1.951 ],
       [5.837 , 4.7631, 5.1781, 8.231 , 7.3223, 0.6906]])

In [22]:
# 5-1
m.max()

9.9724

In [23]:
# 5-2
m.sum(axis=1)

array([29.1637, 25.3385, 38.0722, 23.6387, 32.0221])

In [24]:
np.sum(m,axis=1)

array([29.1637, 25.3385, 38.0722, 23.6387, 32.0221])

In [25]:
# 5-3
m.max(axis=1)

array([9.9724, 7.8431, 9.6384, 5.743 , 8.231 ])

In [27]:
# 5-4
m.mean(axis=0)

array([5.81074, 5.90066, 3.7154 , 5.3664 , 6.02438, 2.82946])

In [28]:
# 5-5
m.min(axis=0)

array([1.7899, 3.7116, 0.8663, 2.0185, 0.9689, 0.5857])

In [139]:
# 5
a = np.random.uniform(0,10,30).reshape(5,6)
a

array([[2.6576939 , 5.74445947, 4.38530468, 0.24880619, 9.94360368,
        2.59366756],
       [1.75829174, 5.59981908, 2.55405185, 8.94216477, 9.14194262,
        3.5528842 ],
       [4.53536548, 8.33018765, 4.75463417, 6.24522583, 3.17569182,
        5.35045336],
       [5.87827113, 5.8345204 , 8.60734802, 4.81893029, 4.45409692,
        7.27556989],
       [3.11973088, 7.4841273 , 2.88969063, 2.87343369, 7.33389001,
        0.11754006]])

In [140]:
# 5-1) 최댓값
a.max()

9.94360368205115

In [141]:
# 5-2) 각 행의 합
a.sum(axis=1)

array([25.57353549, 31.54915425, 32.39155832, 36.86873664, 23.81841257])

In [142]:
# 5-3) 각 행의 최댓값
a.max(axis=1)

array([9.94360368, 9.14194262, 8.33018765, 8.60734802, 7.4841273 ])

In [143]:
# 5-4) 각 열의 평균
a.mean(axis=0)

array([3.58987062, 6.59862278, 4.63820587, 4.62571215, 6.80984501,
       3.77802302])

In [144]:
# 5-5) 각 열의 최솟값
a.min(axis=0)

array([1.75829174, 5.59981908, 2.55405185, 0.24880619, 3.17569182,
       0.11754006])

Q6. Sorting

In [29]:
score = np.array([[1,2,3,4],[46,99,100,71],[81,59,90,100]])
score

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [30]:
# 영어 성적을 argsot()
indices = np.argsort(score[1])
indices

array([0, 3, 1, 2], dtype=int64)

In [31]:
# 내림차순
indices[::-1]

array([2, 1, 3, 0], dtype=int64)

In [32]:
# 모든 행을 영어성적 내림 차순 기준으로 정렬
score[:,indices[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

In [33]:
# 한 줄로
score[:, np.argsort(score[1])[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

In [43]:
# 6
x = np.array([[ 1, 2, 3, 4],
[ 46, 99, 100, 71],
[ 81, 59, 90, 100]])

sort = x.argsort(axis=1)[1]
sort

x[:,sort]

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

Q7. 주사위 100번

In [34]:
np.random.seed(2021)
dice = np.random.randint(1,7,100)
dice

array([5, 6, 2, 1, 6, 5, 4, 6, 6, 6, 1, 5, 2, 6, 2, 2, 5, 6, 3, 3, 1, 4,
       2, 1, 3, 4, 5, 6, 1, 6, 2, 3, 6, 2, 6, 2, 3, 3, 5, 6, 3, 4, 2, 3,
       3, 1, 3, 5, 6, 4, 4, 2, 2, 2, 3, 6, 4, 4, 5, 4, 2, 5, 2, 2, 5, 4,
       6, 4, 4, 4, 3, 2, 4, 3, 6, 3, 3, 1, 5, 4, 2, 4, 2, 5, 3, 4, 2, 3,
       6, 3, 6, 3, 4, 5, 6, 2, 2, 6, 1, 6])

In [35]:
np.mean(dice)

3.7

In [42]:
# 7
a = np.random.randint(1,7, 100)
a.mean()

3.56

In [37]:
# dice array에서의 고유값
np.unique(dice)

array([1, 2, 3, 4, 5, 6])

In [38]:
# dice array에서 고유값 및 그 갯수
np.unique(dice, return_counts=True)

(array([1, 2, 3, 4, 5, 6]), array([ 8, 21, 19, 18, 13, 21], dtype=int64))

In [39]:
unique, counts = np.unique(dice, return_counts=True)
dict(zip(unique, counts))

{1: 8, 2: 21, 3: 19, 4: 18, 5: 13, 6: 21}

Q8. 정규분포, 주식

In [42]:
# 5개만 먼저 테스트
np.random.seed(2021)
rate = np.random.normal(0,0.01,5)
price = 10000
for i in range(5):
    price = np.round(price * (1+rate[i]))
    print(int(price), end=' ')

10149 10218 10175 10093 10149 

In [47]:
# 250개
np.random.seed(2021)
rate = np.random.normal(0,0.01,250)
price = 10000
price_list = []
for i in range(250):
    price = price + np.round(price*rate[i])
    price_list.append(price)
price_array = np.array(price_list, dtype=np.int32)
price_array[-10:]

array([12072, 12210, 12255, 12359, 12292, 12262, 12136, 12010, 11984,
       12113])

In [49]:
np.random.seed(2021)
rate = np.random.normal(0,0.01,250)
price = 10000
price_array = np.empty(250, dtype=np.int32)

for i in range(250):
    price = price + np.round(price*rate[i])
    price_array[i] = price

price_array[-10:]


array([12072, 12210, 12255, 12359, 12292, 12262, 12136, 12010, 11984,
       12113])

In [ ]:
# 8 
# rate => array,  10000 + 10000 *r
......