In [3]:
import numpy as np

In [5]:
# 1
a = np.array([[10,20,30,40],[50,60,70,80]])
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [12]:
# 2
m = np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9],[10, 11, 12, 13, 14]])
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [13]:
# 2-1)
m[1,2]

7

In [14]:
# 2-2)
m[2,4]

14

In [15]:
# 2-3)
m[1, 1:3]

array([6, 7])

In [16]:
# 2-4)
m[1:3,2]

array([ 7, 12])

In [17]:
# 2-5)
m[:2,3:]

array([[3, 4],
       [8, 9]])

In [18]:
# 3
f = m.flatten()
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
# 3-1) 
f[f % 3 == 0]

array([ 0,  3,  6,  9, 12])

In [20]:
# 3-2) 
f[f % 4 == 1]

array([ 1,  5,  9, 13])

In [36]:
# 3-3)
a = np.logical_and(f % 3 == 0, f % 4 == 1)
f[a]

array([9])

In [39]:
# 4
a = np.eye(N=5, M=5, dtype=np.int8)
b = np.eye(N=5, M=5, k=1, dtype=np.int8)
c = np.eye(N=5, M=5, k=-1, dtype=np.int8)
a*2 + b*1 +c*3


array([[2, 1, 0, 0, 0],
       [3, 2, 1, 0, 0],
       [0, 3, 2, 1, 0],
       [0, 0, 3, 2, 1],
       [0, 0, 0, 3, 2]], dtype=int8)

In [139]:
# 5
a = np.random.uniform(0,10,30).reshape(5,6)
a

array([[2.6576939 , 5.74445947, 4.38530468, 0.24880619, 9.94360368,
        2.59366756],
       [1.75829174, 5.59981908, 2.55405185, 8.94216477, 9.14194262,
        3.5528842 ],
       [4.53536548, 8.33018765, 4.75463417, 6.24522583, 3.17569182,
        5.35045336],
       [5.87827113, 5.8345204 , 8.60734802, 4.81893029, 4.45409692,
        7.27556989],
       [3.11973088, 7.4841273 , 2.88969063, 2.87343369, 7.33389001,
        0.11754006]])

In [140]:
# 5-1) 최댓값
a.max()

9.94360368205115

In [141]:
# 5-2) 각 행의 합
a.sum(axis=1)

array([25.57353549, 31.54915425, 32.39155832, 36.86873664, 23.81841257])

In [142]:
# 5-3) 각 행의 최댓값
a.max(axis=1)

array([9.94360368, 9.14194262, 8.33018765, 8.60734802, 7.4841273 ])

In [143]:
# 5-4) 각 열의 평균
a.mean(axis=0)

array([3.58987062, 6.59862278, 4.63820587, 4.62571215, 6.80984501,
       3.77802302])

In [144]:
# 5-5) 각 열의 최솟값
a.min(axis=0)

array([1.75829174, 5.59981908, 2.55405185, 0.24880619, 3.17569182,
       0.11754006])

In [43]:
# 6
x = np.array([[ 1, 2, 3, 4],
[ 46, 99, 100, 71],
[ 81, 59, 90, 100]])

sort = x.argsort(axis=1)[1]
sort

x[:,sort]

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

In [42]:
# 7
a = np.random.randint(1,7, 100)
a.mean()

3.56

In [ ]:
# 8 
# rate => array,  10000 + 10000 *r
......